apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: simpleservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simpleservice
  template:
    metadata:
      labels:
        app: simpleservice
        version: "1"
    spec:
      containers:
        - name: simpleservice
          image: "nginx"
        - name: simpleservice-web
          image: mhausenblas/simpleservice:0.5.0
          ports:
           - name: web
             containerPort: 9876
             protocol: TCP       
